<message message-id="1221567952.55.0.837093180008.issue3774@psf.upfronthosting.co.za" list="org.python.python-bugs-list" id="24curvidmwnxfpzg" type="bugs" date="2008-09-16T12:25:52Z" year="2008-01-01" year-month="2008-09-01" year-month-day="2008-09-16" thread-id="umrkbu5t3q7qtmo6"><headers><envelope-from-line>Tue Sep 16 05:26:07 2008</envelope-from-line><from personal="Dan OD" address="report@bugs.python.org">Dan OD &lt;report@bugs.python.org&gt;</from><to personal="python-bugs-list@python.org" address="python-bugs-list@python.org">python-bugs-list@python.org</to><subject normal="[issue3774] tkinter Menu.delete bug">[issue3774] tkinter Menu.delete bug</subject><received>from srv-117c-be06.markmail.marklogic.com ([172.19.8.46])
          by mail-1.a.markmail.int (JAMES SMTP Server 2.3.1) with SMTP ID 146
          for &lt;velma.pena.rice@a.markmail.org&gt;;
          Tue, 16 Sep 2008 05:26:07 -0700 (PDT)</received><received>from smtp-vbr12.xs4all.nl (slb-117n.markmail.marklogic.com [172.19.8.33])
	by mgw-1.public.markmail.int (Postfix) with ESMTP id C06732908006
	for &lt;velma.pena.rice@a.markmail.org&gt;; Tue, 16 Sep 2008 05:26:06 -0700 (PDT)</received><received>from bag.python.org (bag.python.org [194.109.207.14])
	by smtp-vbr12.xs4all.nl (8.13.8/8.13.8) with ESMTP id m8GCQ5d4050120
	for &lt;velma.pena.rice@a.markmail.org&gt;; Tue, 16 Sep 2008 14:26:06 +0200 (CEST)
	(envelope-from python-bugs-list-bounces+velma.pena.rice=a.markmail.org@python.org)</received><received>from bag.python.org (bag [127.0.0.1])
	by bag.python.org (Postfix) with ESMTP id A4F6A1E4016
	for &lt;velma.pena.rice@a.markmail.org&gt;; Tue, 16 Sep 2008 14:26:05 +0200 (CEST)</received><x-original-to>python-bugs-list@python.org</x-original-to><delivered-to>python-bugs-list@bag.python.org</delivered-to><received>from bag.python.org (bag [127.0.0.1])
	by bag.python.org (Postfix) with ESMTP id 8BD6A1E4002
	for &lt;python-bugs-list@python.org&gt;;
	Tue, 16 Sep 2008 14:26:01 +0200 (CEST)</received><x-spam-status>OK 0.000</x-spam-status><received>from bag (HELO bag.python.org) (127.0.0.1)
	by bag.python.org with SMTP; 16 Sep 2008 14:26:01 +0200</received><received>from psf.upfronthosting.co.za (bugs.python.org [88.198.142.26])
	by bag.python.org (Postfix) with ESMTP
	for &lt;python-bugs-list@python.org&gt;;
	Tue, 16 Sep 2008 14:25:52 +0200 (CEST)</received><received>from psf.upfronthosting.co.za (localhost [10.0.0.1])
	by psf.upfronthosting.co.za (Postfix) with ESMTP id 8C6AD78519
	for &lt;python-bugs-list@python.org&gt;;
	Tue, 16 Sep 2008 14:25:52 +0200 (CEST)</received><date>Tue, 16 Sep 2008 12:25:52 +0000</date><x-roundup-name>Python tracker</x-roundup-name><x-roundup-loop>hello</x-roundup-loop><x-roundup-version>1.4.2</x-roundup-version><mime-version>1.0</mime-version><message-id>1221567952.55.0.837093180008.issue3774@psf.upfronthosting.co.za</message-id><x-roundup-issue-status>open</x-roundup-issue-status><x-roundup-issue-files>menu_bug.py, menu_bag.patch, issue3774.diff,
	menu_fix.patch, issue3774_2.diff</x-roundup-issue-files><x-roundup-issue-severity>normal</x-roundup-issue-severity><x-roundup-issue-versions>Python 2.6, Python 2.5, Python 3.0</x-roundup-issue-versions><x-roundup-issue-components>Tkinter</x-roundup-issue-components><x-roundup-issue-keywords>patch, easy, needs review</x-roundup-issue-keywords><in-reply-to>&lt;1220534371.28.0.918007681781.issue3774@psf.upfronthosting.co.za&gt;</in-reply-to><x-roundup-issue-status>open</x-roundup-issue-status><x-roundup-issue-files>menu_bug.py, menu_bag.patch, issue3774.diff,
	menu_fix.patch, issue3774_2.diff</x-roundup-issue-files><x-roundup-issue-severity>normal</x-roundup-issue-severity><x-roundup-issue-versions>Python 2.6, Python 2.5, Python 3.0</x-roundup-issue-versions><x-roundup-issue-components>Tkinter</x-roundup-issue-components><x-roundup-issue-keywords>patch, easy, needs review</x-roundup-issue-keywords><x-beenthere>python-bugs-list@python.org</x-beenthere><x-mailman-version>2.1.10</x-mailman-version><precedence>list</precedence><reply-to>Python tracker &lt;report@bugs.python.org&gt;</reply-to><list-id>List which receives bug reports on Python
	&lt;python-bugs-list.python.org&gt;</list-id><list-unsubscribe>&lt;http://mail.python.org/mailman/options/python-bugs-list&gt;,
	&lt;mailto:python-bugs-list-request@python.org?subject=unsubscribe&gt;</list-unsubscribe><list-archive>&lt;http://mail.python.org/pipermail/python-bugs-list&gt;</list-archive><list-post>&lt;mailto:python-bugs-list@python.org&gt;</list-post><list-help>&lt;mailto:python-bugs-list-request@python.org?subject=help&gt;</list-help><list-subscribe>&lt;http://mail.python.org/mailman/listinfo/python-bugs-list&gt;,
	&lt;mailto:python-bugs-list-request@python.org?subject=subscribe&gt;</list-subscribe><content-type>text/plain; charset="us-ascii"</content-type><content-transfer-encoding>7bit</content-transfer-encoding><sender>python-bugs-list-bounces+velma.pena.rice=a.markmail.org@python.org</sender><errors-to>python-bugs-list-bounces+velma.pena.rice=a.markmail.org@python.org</errors-to><x-virus-scanned>by XS4ALL Virus Scanner</x-virus-scanned></headers><normalized-references><normalized-message-id>1221567952.55.0.837093180008.issue3774@psf.upfronthosting.co.za</normalized-message-id><normalized-in-reply-to>1220534371.28.0.918007681781.issue3774@psf.upfronthosting.co.za</normalized-in-reply-to></normalized-references><body type="text/plain; charset=&quot;us-ascii&quot;"><para depth="0">
Dan OD &lt;<email>djo35@cam.ac.uk</email>&gt; added the comment:

</para><para depth="0">It may be because I'm calling delete incorrectly (I don't think so - see 
below) but I'm getting an error

</para><para depth="0">  File "C:\CCPN\ccpn\python\memops\gui\Menu.py", line 127, in 
deleteMenuItems
    self.delete(0, Tkinter.END)
  File "C:\Python-2.6_svn\lib\lib-tk\Tkinter.py", line 2670, in delete
    if c in self._tclCommands:
TypeError: argument of type 'NoneType' is not iterable

</para><para depth="0">Which can easily be fixed with 

</para><para depth="0">- if c in self._tclCommands:
+ if c and c in self._tclCommands:

</para><para depth="0">line 2670 Tkinter.py

</para><para depth="0">Should I create a patch or have I missed something? Thanks.

</para><footer type="signature" depth="0" hash="1862292865300939731">_______________________________________
Python tracker &lt;<email>report@bugs.python.org</email>&gt;
&lt;<url>http://bugs.python.org/issue3774</url>&gt;
</footer><footer type="noise" depth="0">_______________________________________
</footer><footer type="list-management" depth="0">_______________________________________________
Python-bugs-list mailing list
Unsubscribe:<br/><url>http://mail.python.org/mailman/options/python-bugs-list/velma.pena.rice%40a.markmail.org</url>

</footer></body></message>